name: CutLang-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - root ==6.26.04
  - jupyterlab ==3.0.16
  - metakernel ==0.27.5
  - flex ==2.6.4
  - bison ==3.4
  - make ==4.2.1
  - wget ==1.20.1
