name: Tests

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    container: rootproject/root:6.24.00-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: chmod
      working-directory: .github/workflows
      run: |
        ls -la
        chmod +x ./sendgrid.js
        chmod +x deploy.sh
        chmod +x filter.sh
        chmod +x mail_body.sh 
        chmod +x commit.sh
      
    - name: CutLang Dependencies
      run: |
        apt update
        apt install -y flex bison wget
                   
    - name: Build CutLang
      working-directory: CLA
      run: make
    
    - name: Run Tests
      working-directory: .github/workflows
      run: |
        ./deploy.sh 2>&1 | tee ./raw_output.txt
      
    - name: Filter Output
      working-directory: .github/workflows
      run: |
        ./filter.sh
        cd ../previous; diff raw_output.txt ../workflows/raw_output.txt | tee ../workflows/differences.txt; rm raw_output.txt errors.txt efficacy_charts.txt differences.txt 
        cd ../workflows; cp raw_output.txt errors.txt efficacy_charts.txt differences.txt ../previous/
        mkdir artifacts; mv raw_output.txt errors.txt efficacy_charts.txt differences.txt ./artifacts
        if [ "`cat ${{ github.workspace }}/.github/workflows/artifacts/errors.txt`" != "Errors: " ]; then
          touch flag
        fi
        ./mail_body.sh
    
    - name: Check for Bad Run Flag
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "flag"

    - name: SMTP
      uses: peter-evans/sendgrid-action@v1
      if: steps.check_files.outputs.files_exists == 'true'
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SCRIPT_FILEPATH: ./.github/workflows/sendgrid.js     
        
    - name: Update Artifacts
      if: steps.cache.outputs.cache-hit == 'true'
      run: cd ./.github/workflows ; ./commit.sh ${GITHUB_REF##*/}
      
    - name: Upload Output File
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests (ubuntu-latest)
        path: ./.github/workflows/artifacts
