name: Update conda package macos

on:
  push:
    branches:
      - 'master'
      - 'package_test'

jobs:
  build-conda-macos:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - uses: s-weigand/setup-conda@v1
    - name: Update meta
      id: update_meta
      working-directory: ./scripts/conda
      run: |
        brew install gsed

        export version_cutlang=`cat ../../VERSION`
        echo "::set-output name=VERSION_CUTLANG::$version_cutlang"

        echo "::group::VERSION"
        echo "Inside group $version_cutlang"
        echo "::endgroup::"
        
        gsed -i "/version = /c{% set version = '$version_cutlang' %}" meta.yaml
        sed -i "/cout << \"CLA v/c cout << \"CLA v$version_cutlang\\\t\";" ../../CLA/CLA.Q
        meta=`cat ../../scripts/conda/meta.yaml`
        echo "::group::META"
        echo "Inside group $meta"
        echo "::endgroup::"
        
        export check_version_cutlang=$(conda search -c ${{secrets.PACKAGE_USERNAME}} -f cutlang | grep $version_cutlang)
        echo "::set-output name=CHECK_VERSION_CUTLANG::$check_version_cutlang"
        
        export unelgRepo=$(git remote -v | grep -e 'origin.*unelg')
        echo "::set-output name=UNELG_REPO::$unelgRepo"

    - name: chmod
      working-directory: .github/workflows
      run: |
        ls -la
        chmod +x update_conda_package_macos.sh
        chmod +x update_conda_package_macos_mail_success.js
        chmod +x update_conda_package_macos_mail_error.js


    - uses: s-weigand/setup-conda@v1
    - name: Build and upload conda macos
      if: ${{ !steps.update_meta.outputs.CHECK_VERSION_CUTLANG }}
      working-directory: ./.github/workflows
      run: |
        conda info
        conda install -y anaconda-client conda-build
        ./update_conda_package_macos.sh
      env:
        SUBDIR: "scripts/conda"
        ANACONDA_TOKEN: "${{ secrets.ANACONDA_TOKEN }}"
        PACKAGE_USERNAME: "${{ secrets.PACKAGE_USERNAME }}"

    #- name: SMTP
    #  if: ${{ !steps.update_meta.outputs.CHECK_VERSION_CUTLANG }}
    #  uses: peter-evans/sendgrid-action@v1
    #  env:
    #    SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    #    SCRIPT_FILEPATH: ./.github/workflows/update_conda_package_macos_mail_success.js     